// === EduPlay integration ===
// Generated by /eduplay. See https://app.eduplay.com/docs/getting-started
//
// This is the mock-mode evaluation wiring. To ship for real:
//   1. Register a game at https://app.eduplay.com to get a real placement ID.
//   2. Remove `mock: true` and replace `placementId` with the real value.
//   3. Wire `studentToken` from your parent-portal-issued session URL param.

import { EduPlayWebClient, type EduPlayWebAd } from '@eduplay/sdk-web';

const client = EduPlayWebClient.initialize({
  apiUrl: 'https://api.eduplay.com',
  placementId: 'pl_mock00000000000000000000',
  studentToken: new URLSearchParams(location.search).get('token') ?? '',
  // Mock mode tells the hosted /break iframe to serve bundled mock questions
  // instead of hitting the live API. No real placement / subscription needed
  // for the integration to render end-to-end during evaluation.
  mock: true,
});

client.start();

let pendingAd: EduPlayWebAd | null = null;

function preloadNextAd(): void {
  client.loadAd({
    onAdLoaded: (ad) => {
      pendingAd = ad;
    },
    onAdFailedToLoad: (err) => {
      // eslint-disable-next-line no-console
      console.warn('[EduPlay] load failed', err);
    },
  });
}

preloadNextAd();

// Call this at natural pause points (level complete, lives lost, game over).
// `onReward` fires only on a correct answer; `onResume` always fires after
// the ad dismisses, so put your "return to game" logic there.
// Returns `true` if an ad was actually shown; `false` if none was preloaded
// (the caller should resume the game immediately in that case so it doesn't
// hang waiting for an ad that will never appear).
export function showAdBreak(opts?: {
  onReward?: () => void;
  onResume?: () => void;
}): boolean {
  if (!pendingAd || !pendingAd.isLoaded()) return false;
  pendingAd.show({
    onUserEarnedReward: (reward) => {
      if (reward.amount === 1) opts?.onReward?.();
    },
    onAdDismissed: () => {
      pendingAd = null;
      opts?.onResume?.();
      preloadNextAd();
    },
  });
  return true;
}
// === end EduPlay integration ===
