var atari2600Games = [
    "3-D Tic-Tac-Toe (Atari) – 1980",
    "32 in 1 (Atari) – 1988",
    "A Mysterious Thief (Vidco) – Prototype",
    "A-Team (Atari) – Prototype",
    "Acid Drop (Salu Ltd) – 1992",
    "Advanced Dungeons & Dragons: Tower of Mystery (M-Network) – Prototype",
    "Advanced Dungeons & Dragons: Treasure of Tarmin (M-Network) – Prototype",
    "Advanced Dungeons & Dragons (M-Network)",
    "Adventure (Atari) – 1979",
    "Adventures of the Pink Panther (Probe 2000) – Prototype",
    "Adventures of Tron (M-Network) – 1982",
    "Airlock (Data Age) – 1982",
    "Air Raid (MenAVision)",
    "Air Raiders (M-Network) – 1982",
    "Air-Sea Battle (Atari) – 1977",
    "Alien (20th Century Fox) – 1982",
    "Alien’s Return (Home Vision) – 1983",
    "Alligator People (20th Century Fox) – Prototype",
    "Alpha Beam with Ernie (Atari) – 1983",
    "Amidar (Parker Brothers) – 1982",
    "Angry Video Game Nerd K.O. Boxing (Cinemassacre) – 2009",
    "Anteater (M-Network) – Prototype",
    "Aquaventure (Atari) – Prototype",
    "Arcade Pinball (Sears)",
    "Armor Ambush (M-Network) – 1982",
    "Artillery Duel/Chuck Norris Superkicks (Xonox) – 1983",
    "Artillery Duel/Ghost Manor (Xonox) – 1983",
    "Artillery Duel/Spike’s Peak (Xonox) – 1983",
    "Artillery Duel (Xonox) – 1983",
    "Assault (Bomb) – 1983",
    "Asterix (PAL) (Atari) – 1983",
    "Asteroids (Atari) – 1981",
    "Astroblast (M-Network) – 1982",
    "Atari Video Cube (Atari) – 1983",
    "Atlantis (Imagic) – 1982",
    "Atlantis II (Imagic) – 1982",
    "BMX Airmaster (TNT Games) – 1989",
    "Bachelor Party (Mystique) – 1983",
    "Bachelorette Party (Mystique) – 1983",
    "Backgammon (Atari) – 1979",
    "Bank Heist (20th Century Fox) – 1983",
    "Bank Heist (Action Hi-Tech)",
    "Barnstorming (Activision) – 1982",
    "Basic Math (Atari) – 1977",
    "Basic Programming (Atari) – 1979",
    "Basketball (Atari) – 1978",
    "Battlezone (Atari) – 1983",
    "Beamrider (Activision) – 1984",
    "Beany Bopper (20th Century Fox) – 1982",
    "Beat Em and Eat Em (Mystique) – 1983",
    "Bermuda Triangle (Data Age) – 1982",
    "Berzerk (Atari) – 1982",
    "Big Bird’s Egg Catch (Atari) – 1983",
    "Bionic Breakthrough (Atari) – Prototype",
    "Blackjack (Atari) – 1977",
    "Bloody Human Freeway (Activision) – Prototype",
    "Blue Print (CBS Electronics) – 1982",
    "Bobby Is Going Home (Bit Corporation) – 1983",
    "Boing! (First Star Software) – 1983",
    "Boggle (Atari) – Prototype",
    "Bouncing Baby Bunnies (Telesys) – Prototype",
    "Bowling (Atari) – 1979",
    "Boxing (Activision) – 1980",
    "Brain Games (Atari) – 1978",
    "Breakaway IV (Sears) – 1978",
    "Breakout (Atari) – 1978",
    "Bridge (Activision) – 1981",
    "Buck Rogers: Planet of Zoom (Sega) – 1983",
    "Bugs (Data Age) – 1982",
    "Bugs Bunny (Atari) – Prototype",
    "Bump ‘n’ Jump (M-Network) – 1983",
    "Bumper Bash (Spectravision) – 1983",
    "Burgertime (M-Network) – 1983",
    "Burning Desire (Playaround) – 1983",
    "Busy Police (Zellers) – 1983",
    "Cabbage Patch Kids (Coleco) – Prototype",
    "Cakewalk (Commavid) – 1983",
    "Canyon Bomber (Atari) – 1979",
    "California Games (Epyx) – 1987",
    "Carnival (Coleco) – 1982",
    "Cathouse Blues (Playaround) – 1982",
    "Casino (Atari) – 1979",
    "Centipede (Atari) – 1982",
    "Challenge (Funvision)",
    "Challenge of Nexar (Spectravision) – 1982",
    "Championship Soccer (Atari) – 1980",
    "Chase (Sears)",
    "Chase the Chuck Wagon (Spectravision) – 1983",
    "Checkers (Activision) – 1981",
    "China Syndrome (Spectravision) – 1983",
    "Chopper Command (Activision) – 1982",
    "Chuck Norris Superkicks/Ghost Manor (Xonox) – 1983",
    "Chuck Norris Superkicks/Spike’s Peak (Xonox) – 1983",
    "Chuck Norris Superkicks (Xonox) – 1983",
    "Circus (Sears)",
    "Circus Atari (Atari) – 1980",
    "Coconuts (Telesys) – 1982",
    "Codebreaker (Atari) – 1978",
    "Combat (Atari) – 1977",
    "Combat Two (Atari) – Prototype",
    "Commando (Activision) – 1988",
    "Commando Raid (US Games) – 1982",
    "Communist Mutants from Space (Cassette) (Starpath) – 1982",
    "Concentration (Atari) – 1978",
    "Condor Attack (Ultravision) – 1983",
    "Congo Bongo (Sega) – 1983",
    "Cookie Monster Munch (Atari) – 1983",
    "Cosmic Ark (Imagic) – 1982",
    "Cosmic Commuter (Activision) – 1985",
    "Cosmic Corridor (Zimag) – 1983",
    "Cosmic Creeps (Telesys) – 1982",
    "Cosmic Free Fire (Action Hi-Tech)",
    "Cosmic Swarm (CommaVid) – 1982",
    "Crab Control (Action Hi-Tech)",
    "Crackpots (Activision) – 1983",
    "Crash Dive (20th Century Fox) – 1983",
    "Crazy Climber (Atari) – 1983",
    "Cross Force (Spectravision) – 1983",
    "Crossbow (Atari) – 1988",
    "Cruise Missile (Froggo) – 1987",
    "Crypts of Chaos (20th Century Fox) – 1982",
    "Crystal Castles (Atari) – 1984",
    "Custer’s Revenge (Mystique) – 1983",
    "Dancing Plate (Bit Corporation) – 1982",
    "Dare Diver (Sears)",
    "Dark Cavern (M-Network) – 1982",
    "Dark Chambers (Atari) – 1988",
    "Deadly Discs (Telegames) – 1983",
    "Deadly Duck (20th Century Fox) – 1982",
    "Death Trap (Avalon Hill) – 1983",
    "Decathlon (Activision) – 1983",
    "Deep Scan (Sega) – 1983",
    "Defender (Atari) – 1982",
    "Defender II (Atari) – 1988",
    "Demolition Herby (Telesys) – 1983",
    "Demon Attack (Imagic) – 1982",
    "Demons to Diamonds (Atari) – 1982",
    "Desert Falcon (Atari) – 1987",
    "Diagnostic Cartridge (Atari)",
    "Dice Puzzle (Panda Computer Games) – 1983",
    "Dig Dug (Atari) – 1983",
    "Dishaster (Zimag) – 1982",
    "Dodge ‘Em (Atari) – 1980",
    "Dodger Cars (Sears) – 1980",
    "Dolphin (Activision) – 1983",
    "Donald Duck’s Speedboat (Atari) – Prototype",
    "Donkey Kong (Coleco) – 1982",
    "Donkey Kong Jr (Coleco) – 1983",
    "Double Dragon (Activision) – 1989",
    "Double Dunk (Atari) – 1988",
    "Dragon Treasure (Zellers)",
    "Dragonfire (Imagic) – 1983",
    "Dragonstomper (cassette) (Starpath) – 1982",
    "Dragster (Activision) – 1980",
    "Dumbo’s Flying Circus (Atari) – Prototype",
    "E.T. the Extra-Terrestrial (Atari) – 1982",
    "Earth Attack (Zellers)",
    "Earth Dies Screaming (20th Century Fox) – 1982",
    "Eggomania (US Games) – 1982",
    "Elevator Action (Prototype) (Atari) – 1983",
    "Eli’s Ladder (Simage) – 1982",
    "Encounter at L-5 (Data Age) – 1982",
    "Enduro (Activision) – 1983",
    "Entombed (US Games) – 1982",
    "Escape From The Mindmaster (Cassette) (Starpath) – 1982",
    "Espial (Tigervision) – 1984",
    "Exocet (Panda Computer Games) – 1983",
    "Exocet Missile (John Sands)",
    "Fall Guy (20th Century Fox) – Prototype",
    "Fantastic Voyage (20th Century Fox) – 1982",
    "Fast Eddie (20th Century Fox) – 1982",
    "Fast Food (Telesys) – 1982",
    "Fatal Run (Atari) – 1990",
    "Fathom (Imagic) – 1983",
    "Fighter Pilot (Activision)",
    "Final Approach (Apollo) – 1982",
    "Fire Fighter (Imagic) – 1982",
    "Fire Fly (Mythicon)",
    "Fireball (cassette) (Starpath)",
    "Fisher Price (CCE)",
    "Fishing Derby (Activision) – 1980",
    "Flag Capture (Atari) – 1978",
    "Flash Gordon (20th Century Fox) – 1983",
    "The Fly (US Games)",
    "Football (Atari) – 1978",
    "Frankenstein’s Monster (Data Age) – 1983",
    "Freeway (Activision) – 1981",
    "Frogger (Parker Brothers) – 1982",
    "Frogger, The Official (cassette) (Starpath) – 1983",
    "Frogger II: Threeedeep! (Parker Brothers) – 1984",
    "Frogs and Flies (M-Network) – 1982",
    "Front Line (Coleco) – 1983",
    "Frostbite (Activision) – 1983",
    "Funky Fish (UA Limited) – Prototype",
    "Fun With Numbers (Atari) – 1978",
    "G.I. Joe: Cobra Strike (Parker Brothers) – 1983",
    "Galaxian (Atari) – 1983",
    "Gangster Alley (Spectravision) – 1983",
    "Garfield (Atari) – Prototype",
    "Gas Hog (Spectravision) – 1983",
    "Gauntlet (Answer Software) – 1983",
    "Ghost Manor/Spike’s Peak (Xonox) – 1983",
    "Ghost Manor (Xonox) – 1983",
    "Ghostbusters (Activision) – 1985",
    "Ghostbusters II (Salu) – 1990",
    "Gigolo (Playaround) – 1982",
    "Glacier Patrol (Telegames) – 1983",
    "Glib (Selchow and Righter) – 1983",
    "Golf (Atari) – 1980",
    "Golf (Sears) – 1980",
    "Good Luck, Charlie Brown (Atari) – Prototype",
    "Gopher (US Games) – 1982",
    "Gorf (CBS Electronics) – 1982",
    "Grand Prix (Activision) – 1982",
    "Gravitar (Atari) – 1983",
    "Great Escape (Bomb) – 1983",
    "Gremlins (Atari) – 1984",
    "Grover’s Music Maker (Atari) – Prototype",
    "Guardian (Apollo) – 1982",
    "Gunslinger (Sears) – 1978",
    "Gyruss (Parker Brothers) – 1983",
    "H.E.R.O. (Activision) – 1984",
    "Halloween (Wizard Video) – 1983",
    "Hangman (Atari) – 1978",
    "Harbor Escape (Panda Computer Games) – 1983",
    "Haunted House (Atari) – 1982",
    "Holey Moley (Atari) – Prototype",
    "Home Run (Atari) – 1978",
    "Human Cannonball (Atari) – 1979",
    "Hunt & Score (Atari) – 1978",
    "I Want My Mommy (Zimag) – 1982",
    "Ice Hockey (Activision) – 1981",
    "Inca Gold (Zellers)",
    "Ikari Warriors (Atari) – 1990",
    "Immies & Aggies (Zimag/Emag/VidCo) – Prototype",
    "In Search of the Golden Skull (M-Network) – Prototype",
    "Incredible Hulk (Parker Brothers) – Prototype",
    "Indy 500 (Atari) – 1977",
    "Infiltrate (Apollo) – 1982",
    "International Soccer (M-Network) – 1982",
    "Intuition (Tigervision) – Prototype",
    "Ixion (video game) (Sega) – Prototype",
    "James Bond 007 (Parker Brothers) – 1983",
    "Jawbreaker (Tigervision) – 1982",
    "Journey Escape (Data Age) – 1982",
    "Joust (Atari) – 1983",
    "Jr. Pac-Man (Atari) – 1986",
    "Jungle Fever (Playaround) – 1982",
    "Jungle Hunt (Atari) – 1983",
    "Kabobber (Activision) – Prototype",
    "Kaboom! (Activision) – 1981",
    "Kangaroo (Atari) – 1983",
    "Karate (Ultravision) – 1983",
    "Keystone Kapers (Activision) – 1983",
    "Killer Satellites (Cassette) (Starpath) – 1982",
    "King Kong (Tigervision) – 1982",
    "Klax (Atari) – 1990",
    "Knight on the Town (Playaround) – 1982",
    "Kool-Aid Man (M-Network) – 1983",
    "Kreuzfeuer (Spectravision) – Prototype",
    "Krull (Atari) – 1983",
    "Kung-Fu Master (Activision) – 1987",
    "Kyphus (Apollo) – Prototype",
    "Lady in Wading (Playaround) – 1982",
    "Laser Blast (Activision) – 1981",
    "Laser Gates (Imagic) – 1983",
    "Laser Volley (Zellers) – 1983",
    "Lasercade (20th Century Fox) – Prototype",
    "Lochjaw (Apollo) – 1982",
    "Lock ‘N Chase (M-Network) – 1982",
    "Locomotion (M-Network) – Prototype",
    "London Blitz (Avalon Hill) – 1983",
    "Lord of the Rings: Journey to Rivendell (Parker Brothers) – Prototype",
    "Lost Luggage (Apollo) – 1982",
    "M*A*S*H (20th Century Fox) – 1982",
    "M.A.D. (US Games) – 1982",
    "Magicard (Commavid) – 1981",
    "Malagai (Answer Software) – 1983",
    "Mangia’ (Spectravision) – 1983",
    "Marauder (Tigervision) – 1982",
    "Marine Wars (Konami) – 1983",
    "Mario Bros. (Atari) – 1983",
    "Mark of the Mole (Atari) – Prototype",
    "Master Builder (Spectravision) – 1983",
    "Masters of the Universe: The Power of He-Man (M-Network) – 1983",
    "Math (Sears) – 1977",
    "Math Gran Prix (Atari) – 1982",
    "Maze (Sears) – 1978",
    "Maze Craze: A Game of Cops and Robbers (Atari) – 1980",
    "Maze Mania (Sears) – 1980",
    "McDonald’s (Parker Brothers) – Prototype",
    "MegaBoy (Dynacom)",
    "Megaforce (20th Century Fox) – 1983",
    "Megamania (Activision) – 1982",
    "Meltdown (20th Century Fox) – Prototype",
    "Memory Match (Sears)",
    "Midnight Magic (Atari) – 1986",
    "Millipede (Atari) – 1984",
    "Miner 2049er II (Tigervision) – 1983",
    "Miner 2049er (Tigervision) – 1982",
    "Mines of Minos (CommaVid) – 1983",
    "Miniature Golf (Atari) – 1979",
    "Miss Piggy’s Wedding (Atari) – Prototype (1983)",
    "Missile Command (Atari) – 1981",
    "Missile Control (Video Gems)",
    "Mission 3000 A.D. (Bit Corporation)",
    "Mission Survive (Video Gems)",
    "Mogul Maniac (Amiga) – 1983",
    "Monster Cise (Atari) – Prototype",
    "Montezuma’s Revenge: Starring Panama Joe (Parker Brothers) – 1984",
    "Moon Patrol (Atari) – 1983",
    "Moonsweeper (Imagic) – 1983",
    "MotoRodeo (Atari) – 1990",
    "Motocross Racer (Xonox) – 1984",
    "Mountain King (CBS Electronics) – 1983",
    "Mouse Trap (Coleco) – 1982",
    "Mr. Do! (Coleco) – 1983",
    "Mr. Do’s Castle (Parker Brothers) – 1984",
    "Mr. Postman (Bit Corporation) – 1983",
    "Ms. Pac-Man (Atari) – 1983",
    "My Golf (HES) – 1990",
    "Mystery Science Theater 2600 (Hozer)",
    "Mystic Castle (M-Network)",
    "Name This Game (VidTec) – 1982",
    "Night Driver (Atari) – 1980",
    "Night Stalker (Telegames) – 1988",
    "No Escape! (Imagic) – 1983",
    "Nova Blast (Imagic) – 1983",
    "Nuts (Technovision) – 1983",
    "Ocean City Defender (Zellers)",
    "Off the Wall (Atari) – 1989",
    "Oink! (Activision) – 1982",
    "Omega Race (CBS Electronics) – 1983",
    "Oscar’s Trash Race (Atari) – 1983",
    "Othello (Atari) – 1980",
    "Out of Control (Avalon Hill) – 1983",
    "Outer Space (Sears) – 1977",
    "Outlaw (Atari) – 1978",
    "Pac-Kong (Funvision)",
    "Pac-Man (Atari) – 1982",
    "Panda Chase (Home Vision)",
    "Parachute (Home Vision) – 1983",
    "Party Mix (cassette) (Starpath)",
    "Peekaboo (Atari) – Prototype",
    "Pel￩’s Soccer (Atari) – 1981",
    "Pengo (Atari) – 1984",
    "Pepsi Invaders (Atari) – 1983",
    "Pete Rose Baseball (Absolute Entertainment) – 1989",
    "Phantom Tank (Bit Corporation)",
    "Phaser Patrol (cassette) (Starpath)",
    "Philly Flasher (Mystique) – 1982",
    "Phoenix (Atari) – 1983",
    "Pick Up (20th Century Fox) – Prototype",
    "Picnic (US Games) – 1983",
    "Piece o’ Cake (US Games) – 1983",
    "Pigs in Space (Atari) – 1983",
    "Pinball (Zellers)",
    "Piraten-Schiff (Spectravision)",
    "Pitfall! (Activision) – 1982",
    "Pitfall II: Lost Caverns (Activision) – 1984",
    "Planet of the Apes (20th Century Fox) – Prototype",
    "Planet Patrol (Spectravision) – 1983",
    "Planeten Patrouile (Spectravision)",
    "Plaque Attack (Activision) – 1983",
    "Pleiades (UA Limited) – Prototype",
    "Poker Plus(Sears) – 1979",
    "Polaris (Tigervision)",
    "Pole Position (Atari) – 1983",
    "Pompeii (Apollo) – Prototype",
    "Pong Sports (Sears) – 1977",
    "Pooyan (Konami) – 1983",
    "Popeye (Parker Brothers) – 1983",
    "Porky’s (20th Century Fox) – 1983",
    "Pressure Cooker (Activision) – 1983",
    "Pressure Gauge (John K. Harvey) – Homebrew, released 2000",
    "Private Eye (Activision) – 1984",
    "Pyramid War (S.S.)",
    "Q-bert’s Qubes (Parker Brothers) – 1984",
    "Q-bert (Atari) – 1987",
    "Q-bert (Parker Brothers) – 1984",
    "Quadrun (Atari) – 1983",
    "Quest for Quintana Roo (Sunrise) – 1983",
    "Quest for Quintana Roo (Telegames) – 1988",
    "Quick Step (Imagic) – 1983",
    "Rabbit Transit (cassette) (Starpath)",
    "Race (Sears) – 1977",
    "Racer (Roklan) – Prototype",
    "Racquetball (Apollo) – 1981",
    "Radar Lock (Atari) – 1989",
    "Radar (Zellers)",
    "Raft Rider (US Games) – 1983",
    "Raiders of the Lost Ark (Atari) – 1982",
    "Ram It (Telesys) – 1983",
    "Rampage (Activision) – 1989",
    "Reactor (Parker Brothers) – 1983",
    "RealSports Baseball (Atari) – 1982",
    "RealSports Boxing (Atari) – 1987",
    "RealSports Football (PAL) (Atari) – 1983",
    "RealSports Football (Atari) – 1982",
    "RealSports Soccer (Atari) – 1983",
    "RealSports Tennis (Atari) – 1983",
    "RealSports Volleyball (Atari) – 1982",
    "Red Sea Crossing (Steve Stack, Inc.) – 1983",
    "Revenge of the Beefsteak Tomatoes (20th Century Fox) – 1983",
    "Riddle of the Sphinx (Imagic) – 1982",
    "River Patrol (Tigervision) – 1983",
    "River Raid (Activision) – 1982",
    "River Raid II (Activision) – 1988",
    "Road Runner (Atari) – 1989",
    "Robin Hood/Sir Lancelot – The Joust (Xonox) – 1983",
    "Robin Hood (Xonox) – 1983",
    "Robot Commando Raid (VidTec)",
    "Robot Tank (Activision) – 1983",
    "Roc ‘N Rope (Coleco) – 1984",
    "Rocky and Bullwinkle (M-Network) – Prototype",
    "Rubik’s Cube (Atari) – 1983",
    "Save Mary (Atari) – Prototype",
    "Save Our Ship (Technovision)",
    "Save the Whales (20th Century Fox) – Prototype",
    "Scraper Caper (Tigervision)",
    "Scuba Diver (Panda Computer Games)",
    "Sea Battle (M-Network) – 1982",
    "Sea Hawk (Froggo) – 1988",
    "Sea Hunt (Froggo) – 1988",
    "Seaquest (Activision) – 1983",
    "Secret Quest (Atari) – 1989",
    "Sentinel (Atari) – 1990",
    "Shark Attack (Apollo) – 1982",
    "Shooting Arcade (Atari) – Prototype",
    "Shootin’ Gallery (Imagic) – 1983",
    "Shuttle Orbiter (Avalon Hill) – 1983",
    "Signal Tracing Cartridge (Atari)",
    "Sinistar (Atari) – Prototype",
    "Sir Lancelot (Xonox) – 1983",
    "Six Pack (20th Century Fox) – Prototype",
    "Skate Boardin’: A Radical Adventure (Absolute Entertainment) – 1987",
    "Skeet Shoot (Apollo) – 1981",
    "Skiing (Activision) – 1980",
    "Sky Diver (Atari) – 1979",
    "Sky Jinks (Activision) – 1982",
    "Sky Patrol (Imagic) – Prototype",
    "Sky Skipper (Parker Brothers) – 1983",
    "Slot Machine (Atari) – 1979",
    "Slot Racers (Atari) – 1978",
    "Slots (Sears) – 1979",
    "Smurf: Rescue in Gargamel’s Castle (Coleco) – 1982",
    "Sneak ‘N Peek (VidTec)",
    "Snoopy and The Red Baron (Atari) – 1983",
    "Snow White (Atari) – Prototype",
    "Solar Fox (CBS Electronics) – 1983",
    "Solar Storm (Imagic) – 1983",
    "Solaris (Atari) – 1986",
    "Sorcerer (Mythicon) – 1983",
    "Sorcerer’s Apprentice (Atari) – 1983",
    "Space Attack (M-Network) – 1982",
    "Space Attack (Telegames) – 1988",
    "Space Canyon (Panda Computer Games)",
    "Space Cavern (Apollo) – 1981",
    "Space Chase (Apollo)",
    "Space Combat (Sears) – 1978",
    "Space Grid (Action Hi-Tech)",
    "Space Invaders (Atari) – 1980",
    "Space Jockey (VidTec) – 1981",
    "Space Shuttle: A Journey Into Space (Activision) – 1983",
    "Space War (Atari) – 1978",
    "Spacemaster X-7 (20th Century Fox) – 1983",
    "Speedway II (Sears) – 1977",
    "Spelling (Sears) – 1978",
    "Spiderdroid (Froggo) – 1988",
    "Spider Fighter (Activision) – 1983",
    "Spider-Man (Parker Brothers) – 1983",
    "Spider Maze (K-Tel Vision)",
    "Spike’s Peak (Xonox) – 1983",
    "Spitfire Attack (Milton Bradley) – 1983",
    "Springer (Tigervision) – 1983",
    "Sprintmaster (Atari) – 1988",
    "Spy Hunter (Sega) – 1983",
    "Squeeze Box (US Games) – 1983",
    "Squoosh (Apollo) – Prototype",
    "Sssnake (Data Age) – 1982",
    "Stampede (Activision) – 1981",
    "Star Fox (Mythicon) – 1983",
    "Star Raiders (Atari) – 1982",
    "Star Ship (Atari) – 1977",
    "Star Strike (M-Network) – 1982",
    "Star Strike (Telegames) – 1988",
    "Star Trek: Strategic Operations Simulator (Sega) – 1983",
    "Star Voyager (Imagic) – 1982",
    "Star Wars Return of the Jedi: Death Star Battle (Parker Brothers) – 1983",
    "Star Wars Return Of The Jedi: Ewok Adventure (Parker Brothers) – Prototype",
    "Star Wars: Jedi Arena (Parker Brothers) – 1983",
    "Star Wars: The Arcade Game (Parker Brothers) – 1984",
    "Star Wars: The Empire Strikes Back (Parker Brothers) – 1982",
    "Stargate (Atari) – 1984",
    "Stargunner (Telesys) – 1982",
    "Starmaster (Activision) – 1982",
    "Steeplechase (Video Gems)",
    "Steeplechase (Sears) – 1980",
    "Stella’s Stocking (AtariAge) – 2007",
    "Stellar Track (Sears) – 1981",
    "Strategy X (Konami) – 1983",
    "Strawberry Shortcake: Musical Match-ups (Parker Brothers) – 1983",
    "Street Racer (Atari) – 1977",
    "Sub Scan (Sega) – 1983",
    "Submarine Commander (Sears) – 1982",
    "Subterranea (Imagic) – 1983",
    "Suicide Mission (cassette) (Starpath)",
    "Summer Games (Epyx) – 1987",
    "Super Baseball (Atari) – 1988",
    "Super Baumeister (Spectravision)",
    "Super Breakout (Atari) – 1982",
    "Super Challenge Baseball (M-Network) – 1982",
    "Super Challenge Baseball (Telegames) – 1988",
    "Super Challenge Football (M-Network) – 1982",
    "Super Challenge Football (Telegames) – 1988",
    "Super Cobra (Parker Brothers) – 1983",
    "Super Crush (Tigervision) – Prototype",
    "Super Football (Atari) – 1988",
    "Superman (Atari) – 1979",
    "Superman (Sears) – 1979",
    "Surf’s Up (Amiga) – Prototype",
    "Surfer’s Paradise: But Danger Below! (Video Gems)",
    "Surround (Atari) – 1977",
    "Survival Island (cassette) (Starpath)",
    "Sword of Saros (cassette) (Starpath)",
    "Swordfight (M-Network) – Prototype",
    "Swordquest: Airworld (Atari) – Prototype",
    "Swordquest: Earthworld (Atari) – 1982",
    "Swordquest: Fireworld (Atari) – 1982",
    "Swordquest: Waterworld (Atari) – 1983",
    "Tac-Scan (Sega) – 1983",
    "Tank Brigade (Panda Computer Games) – 1983",
    "Tank City (Action Hi-Tech)",
    "Tank Plus (Sears) – 1977",
    "Tanks But No Tanks (Zimag) – 1983",
    "Tapeworm (Spectravision) – 1982",
    "Tapper (Sega) – 1984",
    "Target Fun (Sears) – 1977",
    "Task Force (Froggo) – 1988",
    "Tax Avoiders (American Videogame) – 1983",
    "Taz (Atari) – 1984",
    "Tempest (Atari) – Prototype",
    "Tennis (Activision) – 1981",
    "Texas Chainsaw Massacre (Wizard Video) – 1983",
    "The Activision Decathalon (Activision) – 1983",
    "The Entity (20th Century Fox) – Prototype",
    "The Music Machine (Sparrow) – 1983",
    "Threshold (Tigervision) – 1983",
    "Thunderground (Sega) – 1983",
    "Thwocker (Activision) – Prototype",
    "Time Pilot (Coleco) – 1983",
    "Time Warp (Zellers)",
    "Title Match Pro Wrestling (Absolute Entertainment) – 1989",
    "Tomarc The Barbarian (Xonox) – 1983",
    "Tomcat: The F-14 Fighter Simulator (Absolute Entertainment) – 1989",
    "Tooth Protectors – 1983",
    "Towering Inferno (US Games) – 1982",
    "Toyshop Trouble (AtariAge)",
    "Track & Field (Atari) – 1984",
    "Treasure Below (Video Gems)",
    "Trick Shot (Imagic) – 1983",
    "Tron: Deadly Discs (M-Network) – 1982",
    "Tunnel Runner (CBS Electronics) – 1983",
    "Turmoil (20th Century Fox) – 1982",
    "Turmoil (Zellers)",
    "Tutankham (Parker Brothers) – 1983",
    "Up’n Down (Sega) – 1984",
    "Vanguard (Atari) – 1982",
    "Venetian Blinds Demo (Activision) – Prototype",
    "Venture (Coleco) – 1982",
    "Video Checkers (Atari) – 1980",
    "Video Chess (Atari) – 1979",
    "Video Life (Commavid) – 1981",
    "Video Olympics (Atari) – 1977",
    "Video Pinball (Atari) – 1981",
    "Vong (Rick Skrbina) – Homebrew, released 2008",
    "Vulture Attack (K-Tel Vision)",
    "Wabbit (Apollo)",
    "Wall Ball (Avalon Hill) – 1983",
    "War Zone (Action Hi-Tech)",
    "Warlords (Atari) – 1981",
    "Warplock (Data Age) – 1982",
    "Weird Bird (US Games)",
    "Wing War (Imagic) – Prototype",
    "Winter Games (Epyx) – 1987",
    "Wizard (Atari) – Prototype",
    "Wizard of Wor (CBS Electronics) – 1982",
    "Word Zapper (US Games) – 1982",
    "Worm War I (20th Century Fox) – 1982",
    "X-man (Gamex) – 1983",
    "Xenophobe (Atari) – 1990",
    "Xevious – Prototype",
    "Yars’ Revenge (Atari) – 1982",
    "Z-Tack (Bomb) – 1983",
    "Zaxxon (Coleco) – 1982",
    "Zoo Fun (Home Vision)"
];
var randomPick = atari2600Games[Math.floor(Math.random() * atari2600Games.length)];
console.log(randomPick);
